### ISSUE TITLE
Converting a local scheme file to a theme

### ISSUE THREAD

**Issue by LandonSchropp** [base16-builder/base16-builder#97]
I'm trying to compile a local scheme file into a template. When I run `base16-builder -s theme.yml -t vim`, I get the following error:

```
fatal: You did not supply valid arguments. Run 'base16-builder --help' for guidance.
```

I'm assuming I'm doing something wrong, but it's not clear what that is from the error message. Am I not allowed to pass a file directly to the `-s` flag? How would I do it instead?

Here's `theme.yml`:

``` yml
# My personal Vim theem, based on Atelier Sulphurpool
scheme: "Landon's Theme"
author: "Landon Schropp (http://landonschropp.com)"
base00: "202746"
base01: "374375"
base02: "5c689b"
base03: "6b7394"
base04: "898ea4"
base05: "a4abc4"
base06: "dfe2f1"
base07: "f5f7ff"
base08: "c94c60" # Red
base09: "c76b29" # Orange
base0A: "c08b30" # Yellow
base0B: "5fb391" # Green
base0C: "38bfef" # Aqua
base0D: "4093d6" # Blue
base0E: "6679cc" # Purple
base0F: "aa5778" # Brown
```

Thanks in advance!
